commonLabels:
  app.kubernetes.io/part-of: kubeseal-web

images:
  - name: kubeseal-web
    newName: "mrsaints/kubeseal-web"
    newTag: "latest"

replicas:
  - name: kubeseal-web
    count: 1

configMapGenerator:
  - name: kubeseal-web-config
    # behavior: merge
    literals:
      - KSWEB_SEALED_SECRETS_CONTROLLER_NAMESPACE=kube-system
      - KSWEB_SEALED_SECRETS_CONTROLLER_NAME=sealed-secrets-controller
    # - KSWEB_LOG_LEVEL=info

resources:
  - ./deployment.yml
  - ./service.yml
