---
apiVersion: v1
kind: Service
metadata:
  name: kubeseal-web
  labels:
    app.kubernetes.io/name: kubeseal-web
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: kubeseal-web
